nodeLinker: node-modules

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.0.2.cjs

preferInteractive: true
preferReuse: true
tsEnableAutoTypes: true
enableTelemetry: false

httpProxy: "http://127.0.0.1:20171"
httpsProxy: "http://127.0.0.1:20171"
