version: '3.8'

services:
  hydro:
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ..:/workspace:cached
      - testdata:/data/file
    command: sleep infinity
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
  testdata: