version: '3.9'

services:
  db:
    image: mongo:4-focal
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
  hydro:
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - mongo
    volumes:
      - ..:/workspace:cached
      - testdata:/data/file

volumes:
  mongodb-data:
  testdata: